SELECT
    YEAR(TP.TRANSACTION_DATE_TIME) AS ANIO,
    B.NAME AS BANCO,
    P.NAME AS PROGRAMA,
    SUM(CASE WHEN TP.TYPE = 'CREDIT' THEN TP.POINTS ELSE 0 END) AS TOTAL_CREDITOS,
    SUM(CASE WHEN TP.TYPE = 'DEBIT' THEN TP.POINTS ELSE 0 END) AS TOTAL_DEBITOS,
    COUNT(DISTINCT TP.CARDHOLDER_ID) AS CARDHOLDERS_UNICOS
FROM
    GENNIUS_XYZ.COMPANY_BRONZE_LAYER.TARJETA_PUNTOS TP
    JOIN GENNIUS_XYZ.COMPANY_BRONZE_LAYER.BANCO B ON TP.BANK_ID = B.BANKID
    JOIN GENNIUS_XYZ.COMPANY_BRONZE_LAYER.PROGRAMA P ON TP.PROGRAM_ID = P.PROGRAMID
GROUP BY
    ANIO, BANCO, PROGRAMA
ORDER BY
    ANIO, BANCO, PROGRAMA;